### ISSUE TITLE
Metric export exports both metrics and rules

### ISSUE THREAD

**Issue by dupuisa** [lequal/i-CodeCNES#107]
### Expected behavior
Export metrics exports only metrics.

### Actual behavior
CS company fouds out that metrics export exports both metrics and rules.

### Steps to reproduce behavior
Export metrics

### Detection version
V3.0.0

**Comment by WaldoFR** [comment]
Hi,

We decided to not make the export button relative to the opened view anymore so it's possible to export both metrics and violations. 

However, it's still possible to export only metrics by disabling all violations checkers and enabling all metrics in **_Window > Preferences > i-Code CNES_** before running the analysis.

Regards,
Omar Waldmann
