### ISSUE TITLE
Metrics Export enhancement

### ISSUE THREAD

**Issue by dupuisa** [lequal/i-CodeCNES#109]
CS company proposal

### Expected behavior
Export display could be 
- XML  « analysisRuleId=SH.MET » and then < resultTypeMetric=Nesting   resultValue="1.0"> for each metric
- CSV : column metric management 

### Actual behavior
Metrics export do not display all metrics for the same operations in the same line.

### Detection version
V3.0.0

**Comment by WaldoFR** [comment]
Hi,

This XML export file's structure was designed to be compliant with other tools export, that's why we won't change it. However, it's possible to add an other XML export in analyzer's extension point.

Regards,
Omar Waldmann
