### ISSUE TITLE
Application crash on some files

### ISSUE THREAD

**Issue by dupuisa** [lequal/i-CodeCNES#110]
### Expected behavior
no crash

### Actual behavior
CS company founds out that the application crashes on launching analyse on specific files

### Steps to reproduce behavior
Launch analyse on attached files

### Detection version
V3.0.0

[Bug-iCode.zip](https://github.com/lequal/i-CodeCNES/files/1542742/Bug-iCode.zip)

**Comment by begarco** [comment]
Only Unix files are supported by i-Code, your files have DOS format.

Use dos2unix command to convert your file in the compliant format.
