### ISSUE TITLE
Activate or deactivate  all the rules in one click

### ISSUE THREAD

**Issue by antonyricard** [lequal/i-CodeCNES#111]
### Expected behavior
Activate or deactivate  all the rules in one click

### Actual behavior
Currently, we have to activate or deactivate the rules one by one 

### Detection version
V3.0.0

**Comment by WaldoFR** [comment]
Hi, 

To enable/disables all rules, please select the checkbox on the column in Window > Prerences > i-Code CNES
![image](https://user-images.githubusercontent.com/10857454/37920188-7de5a704-3126-11e8-927d-ca6c93a21b94.png)

Regards,
Omar
