### ISSUE TITLE
COM.DATA.Initialisation

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#113]
Implementation of the rule COM.DATA.Initialisation

## Description 
> It is mandatory to initialize a variable before it's use.

### Function declaration
Description : The rule is not handling some types of functions declaration. The problem is the same one as defined for several rules in #49 .
- [x] Fix status

## State of the implementation

- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
On progress

**Comment by brigittehuynh** [comment]
Corrected violations and updated unit tests
