### ISSUE TITLE
COM.DATA.Invariant

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#114]
Implementation of the rule COM.DATA.Invariant

## Description 
> It is mandatory to define as constants any invariant object.

### False positives when using awk 
Code : `awk 'BEGIN { FS = " "; StartType = 0; StartEnum = 0; typeName=""; }`
Result:  a violation of the rule is raisen on `typename`.
- [x] Fix status

### False positive when using ++ in a loop
Code : `  (( PREPAR_UNE_SEUL_FOIS++ )) `
- [x] Fix status

### Function declaration
Description : The checker is not handling some types of functions declaration. The problem is the same one as defined for several rules in #49 .
- [x] Fix status

## State of the implementation
- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
I chose to correct the false positive in the for (( ...  )) construct by ignoring the code between for (( and done.
Other choices could have been made, such as ignoring the for (( ...)) code, or treating the for as a mini function, with its own variables. This last solution would have been better but far more time consuming.
