### ISSUE TITLE
COM.FLOW.FilePath

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#115]
Implementation of the rule COM.FLOW.FilePath

## Description 
> It is mandatory to use language's configuration file or call parameter or a variable to access a file.

### Wrong implementation
Description : The current implementation of the rule is getting it wrong. It's verifying if a file extension (considered as `[\.][a-zA-Z][^\.]{0,5}`) is involved in a variable assignation, after a redirection `>`, a `cat`, a `rm`or a `more`. (example : `MODULE=example.ksh`). 
- [x] Fix status

## State of the implementation

- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
The localization remains for the moment the basic detection of functions, not including nested ones.

Compared with COM.FLOW.FileExistence, the n and z options (string options) were removed. This might need to be done in COM.FLOW.FileExistence, or not.
