### ISSUE TITLE
COM.NAME.Homonymy

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#118]
Implementation of the rule COM.NAME.Homonymy.

## Description 
> Homonymy, the fact of using the same names for global, external, and functions variables, is forbidden.

### False positive when a variable is declared
Description : when using a local variable in the function where it's declared a violation is detected.
- [x] Fix status

### Inaccurate violation message 
Description : Named variable in the violation message is different from the code message. For instance, if the variable name is `_dir` the message of the violation will contain only `dir`.
- [x] Fix status

### False positive on variable of different names
Description : A violation is sometimes detected on two variable with different name, for instance, `_c` and `c` are considered both as the same variables. It seems the problem is based on 
- [x] Fix status

## State of the implementation

- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
The false positives and incorrect messages are no longer present in the 3.1.0-dev version. Test files updated accordingly to test these issues. 
The localization is also correctly implemented (old version, before the function class was implemented).
