### ISSUE TITLE
COM.PRES.Indent

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#119]
Implementation of the rule COM.PRES.Indent.

## Description 
> Code indentation must be spaces (no tabulation).

### Awk command handling
Description : The checker raises violation when using awk
- [x] Fix status

### Quotes and double quotes handling
Description : Behaviour of the checker becomes inaccurate when reading quotes or double quotes.
- [x] Fix status

### Cases statements handling
Description : Case statements is not handled correctly, which leads it to raise false positives.
- [x] Fix status

### Comments handling
Description : The checker raises false positives after commented lines. This problem might be due by `ELSE`, `CONT`, `currentPos` and `desiredPos` in the lex.
- [x] Fix status

### Analysis failure on braces
Description : It seems that the number of `{}` braces accounting cause crashes of the anaylsis. Might come from the item  `+([0-9])` of the case. For instance the code beetween braces in : 
`[[ $? != 0 ]] && { echo >&2 the required \"message\" command is not in your PATH; exit 1; }`
- [x] Fix status

### Forbidden increasing of identation not handled
Description :  Bad increasing of indentation is not handled by the checker. For example :
``` 
 ma_fonction_affine ()
{
   if [ $# -ne 3 ]
   then
      my_function=$code_error_nbargs
   else
      printf "Calling : p1=%s p2=%s p3=%s\n" $1 $2 $3
              # operation : y = ax + b
        let y=$1*$2+$3
           printf "y=%s\n" $y
                       my_function=$y
   fi
}
``` 
- [x] Fix status

### Function declaration
Description : The checker is not handling some types of functions declaration. The problem is the same one as defined for several rules in #49 .
- [x] Fix status

## State of the implementation

- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
Localization added via #49
