### ISSUE TITLE
SH.FLOW.CheckCodeReturn

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#121]
Implementation of the rule SH.FLOW.CheckCodeReturn.

## Description 
> It's mandatory to verify error's code returned by any command or execution called by a shell script.

### Commands execution handling
Description : Parseur behaviour becomes inaccurate when reading a command execution.
- [ ] Fixed

### Pipe handling
Description : On a pipiline, where the first function hsouldn't be verified and that there is only one function to verify in the pipe line, the violation message is the one intended to simples functions. Also, raising false positive on `||` use.
Code example : 
* `grep "Date :" $ficresarc | awk '{print $3}' > datejul.tmp`
* `cd -- "$idir" || { echo >&2 can not cd to "$idir"; exit 1; }`
- [x] Fixed

### Test handling
Description : The checker raise a violation when the test returned isn't like `if [ $? -eq 0]`.
- [x] Fixed

### Last file's violation is on a wrong line
Description : The last violation detected by the checker on a file is set on the previous line of the violation.
Code example : 
```
cd testdir
date +%d_%m_%y > newfile
retour=$?
ls
```
- [x] Fixed

### Function declaration
Description : The checker is not handling some types of functions declaration. The problem is the same one as defined for several rules in #49 . This might also be the reason a false positive violation raise when a function name isn't clearly defined.
- [x] Fixed

### Exports handling
Description : The checker raises false positive on export use.
Code example : `export –f funcName`
- [x] Fixed

## State of the implementation

- [x] Violation raising
- [x] Localization
- [x] Unit tests

**Comment by brigittehuynh** [comment]
The rule is corrected, with a limitation: $(_command_) style commands are not looked into. They do not interfere with the rest on the code.
