### ISSUE TITLE
SH.MET.RatioComment

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#124]
### Expected behavior
Only real function are detected as function

### Actual behavior
Parser wrongly considers some tokens as function declaration.

### Steps to reproduce behavior
Analyse the following line : 
```
local pytestTests=`$buildDir/run py.test --collectonly | grep "<Function" | sed "s/<.*Function '//g" | sed "s/'>//g" | tr "\n" " "`
```

### Detection version
2.0

**Comment by brigittehuynh** [comment]
It seems that the previous rewriting of the rule must have corrected the issue, as the behavior is no longer reproduced.
