### ISSUE TITLE
Test files may have a "contains" instead of an "equals" to check the location value

### ISSUE THREAD

**Issue by brigittehuynh** [lequal/i-CodeCNES#147]
### Expected behavior
Test files should check that the location found equals the expected location 

### Actual behavior
In the Shell COM.PRES.Indent rule the test checked if one of the locations contained the other, resulting in a false positive (ma_fonction_affine included in ma_fonction_affine2)
The test has been corrected in the COM.PRES.Indent rule but the tests of the other rules need checking.

### Steps to reproduce behavior
In test files, the testRunWithError method needs location.contains(LOCATIONS[index]) changed to location.equals(LOCATIONS[index]) in the value verification part

### Detection version
3.1.0-dev

**Comment by begarco** [comment]
Currently, there is only one generic `testRunWithError` function in `icode-core/src/main/java/fr/cnes/icode/test/ICodeCheckerTester.java`.

It contains `assertTrue(location.contains(locations[index]));` so we have to change it to `assertTrue(location.equals(locations[index]));`.
