### ISSUE TITLE
COM.FLOW.FileExistence false positive

### ISSUE THREAD

**Issue by furmanc** [lequal/i-CodeCNES#160]
### Expected behavior
In case a file is get from a curl command, the check of the file existence cannot be performed before.
line 144 of attached file : the file is get from curl command
line 148 of attached file : the existence of the file is checked as "if [[ ${file} =~ "Error" || ${file} == "" ]]"

The existence of the file is checked so we do not expect to have a i-code error

### Actual behavior
The erreur COM.FLOW.FileExistence is raised because i-code checks the file existence by searching the  keyword patterns : "test -option file", "test ! -option file", "-option file" or "! -option file"

### Steps to reproduce behavior
see expected behavior

### Detection version
V3.0.1

**Comment by begarco** [comment]
Does the problem still araise in 3.1.0?

**Comment by furmanc** [comment]
I have just check the new feature/fixes of V3.1.0 on i-code page "https://github.com/lequal/i-CodeCNES". There is nothing related to COM.FLOW.FileExistence so the behavior shall be the same with V3.1.0.

**Comment by begarco** [comment]
Could you provide a minimal code sample trigerring a false positive?

**Comment by begarco** [comment]
The file existence should be tested before testing file content.

See https://www.cyberciti.biz/faq/unix-linux-test-existence-of-file-in-bash/

No fix to implement for i-Code.
