### ISSUE TITLE
Files handling and recursive analysis issue

### ISSUE THREAD

**Issue by CarlosMazo** [lequal/i-CodeCNES#161]
### Expected behavior
Run icode analysis of Fortran code of a full project.

### Actual behavior
Not able to run icode analysis of a full project, I have to go folder by folder.
File handling issue found

### Steps to reproduce behavior
I have tried executing analysis of a project two ways (the two found in the documentation):

`icode 'projectFolder/*'` -- Trying to make icode command to analyse Fortran files in every folder under projectFolder, I get no analysis, the report has just the headers, seems not finding any Fortran file.

`icode` '**/*'` -- The analysis works, I get the report, but I have to first cd in every folder with Fortran files, so I get one report by each folder. If I execute this command from the root of the project (even in a small project) the app opens thousands of files, until the process throw an error because of too many files opened. Seems that there is an issue in the files handing. Attached log for this execution

Is there any other way to execute via command line a full project analysis? Maybe there is something wrong in my configuration? Thanks a lot

### Detection version
1.1.0

**Comment by CarlosMazo** [comment]
[execution_log.log](https://github.com/lequal/i-CodeCNES/files/2880464/execution_log.log)

**Comment by begarco** [comment]
Hi Carlos, can you try this **non official** version and tell me if you can run an analysis on **huge** projects ? 

https://github.com/Facthunder/i-CodeCNES/releases/tag/3.2.0-dev

With this version you should be able to: 
- provide directories to i-Code like that `icode src` or simply `icode`
- search recursively files
- open files one after the other

**Comment by CarlosMazo** [comment]
Hi, I have tried but seems that something is wrong with the release.

- The dev.zip folder is not prepared to be executed (not sure if it is thought for that purpose)
- The source code in the zip folder fails trying to execute  `maven install` in order to get the target folder with the executable, configuration, etc... I get dependencies errors;

`Could not resolve dependencies for project fr.cnes.icode:shell-rules:jar:3.2.0-dev: Could not find artifact fr.cnes.icode:fr.cnes.analysis.tools.shell.metrics:jar:3.2.0-dev in central`

Tried to install these dependencies manually too (as they are available as jar in the dev.zip folder) but not working either

Thanks,
Carlos

**Comment by begarco** [comment]
Normally if you run the script `icode` which is in the zip in folder named icode too you should be able to run icode.

In the icode directory you should have:
- the icode script for Unix systems
- the icode.bat script for Windows systems 
- the main jar
- a folder containing needed icode plugins

**Comment by CarlosMazo** [comment]
Executing icode script for Unix I got the following error:

`Exception in thread "main" java.lang.NoClassDefFoundError: fr.cnes.icode.application.ICodeApplication
   at gnu.java.lang.MainThread.run(libgcj.so.14)
Caused by: java.lang.ClassNotFoundException: fr.cnes.icode.application.ICodeApplication not found in gnu.gcj.runtime.SystemClassLoader{urls=[], parent=gnu.gcj.runtime.ExtensionClassLoader{urls=[], parent=null}}
   at java.net.URLClassLoader.findClass(libgcj.so.14)
   at java.lang.ClassLoader.loadClass(libgcj.so.14)
   at java.lang.ClassLoader.loadClass(libgcj.so.14)
   at gnu.java.lang.MainThread.run(libgcj.so.14)
`

**Comment by begarco** [comment]
I do not reproduce your error.

- I have created a new Debian vm
- And then I ran those commands :
```
wget https://github.com/Facthunder/i-CodeCNES/releases/download/3.2.0-dev/icode-3.2.0-dev.zip
unzip icode-3.2.0-dev.zip
chmod +x icode/icode
cp icode/icode icode/icode.sh
icode/icode icode/icode.sh
```
And it worked
