### ISSUE TITLE
Release Candidate 3.2.0-dev CLI - symbolic links cause Analysis failure : Location unreachable

### ISSUE THREAD

**Issue by twenty-19** [lequal/i-CodeCNES#162]
## Expected behavior

Run icode analysis of Fortran code in a project

## Actual behavior

Unable to run analysis on valid symbolic links to f90 files, analysis works OK on normal f90 files

## Steps to reproduce behavior

- make a symbolic link to a fortran file

- run icode -c "Fortran 90"

[SEVERE] i-Code CNES analysis encountered a problem.

Analysis failure : Location unreachable.
CheckerId: fr.cnes.analysis.tools.fortran90.rules.COMNAMEHomonymy
File: ./basic_routines.f90
Line:411
Column:2

ls -la ./basic_routines.f90
./basic_routines.f90 -> ../basic_routines.f90

**Comment by begarco** [comment]
Does the file exist in the parent directory?

In our tests we get the following:
```xml
begarco@localhost /tmp/issue162 $ ls -lR
.:
total 4
-rwxrwxrwx 1 begarco begarco 3932 Mar  9 12:10 error.f90
drwxrwxrwx 1 begarco begarco  512 Mar  9 14:23 subdir

./subdir:
total 0
lrwxrwxrwx 1 begarco begarco 12 Mar  9 14:23 error.f90 -> ../error.f90


begarco@localhost /tmp/issue162 $ icode -c "Fortran 90" subdir
<?xml version="1.0" encoding="UTF-8"?>
<analysisProject analysisProjectName="Unknown" analysisProjectVersion="1.0.0">
  <analysisInformations analysisConfigurationId="analysis1" analysisDate="2019-03-09" author="i-Code CNES Analyzer" />
  <analysisFile language="fr.cnes.icode.fortran90" fileName="subdir/error.f90" />
  <analysisRule analysisRuleId="F90.MET.ComplexitySimplified">
    <result resultId="1" fileName="subdir/error.f90" resultLine="1" resultTypePlace="method" resultNamePlace="MAIN PROGRAM" resultValue="1.0" />
  </analysisRule>
  ...
</analysisProject>
```

**Comment by twenty-19** [comment]
argh, it's not the symbolic link causing the problem... (and yes the file exists in the parent directory)

l did another little test - using the 3.1.0 version of icode on the same file (same symbolic link as before)

this is the result - you can see the same error message at the top of the output, but it continues with the analysis

icode -c "Fortran 90" basic_routines.f90

!SESSION 2019-03-10 12:36:23.386 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_AU
Framework arguments:  -c Fortran 90 basic_routines.f90
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -c Fortran 90 basic_routines.f90

!ENTRY fr.cnes.analysis.tools.analyzer 4 0 2019-03-10 12:36:24.697
!MESSAGE [ERROR]
Class: basic_routines.f90
Method: fr.cnes.analysis.tools.fortran90.rules.COMNAMEHomonymy

Message:i-Code CNES analysis encountered a problem.

Analysis failure : Location unreachable.
CheckerId: fr.cnes.analysis.tools.fortran90.rules.COMNAMEHomonymy
File: basic_routines.f90
Line:411
Column:2
Last word scanned: [End Subroutine] [69 110 100 32 83 117 98 114 111 117 116 105 110 101 ]
Please report this issue on : https://github.com/lequal/i-CodeCNES/issues/
<?xml version="1.0" encoding="UTF-8"?>
<analysisProject analysisProjectName="Unknown" analysisProjectVersion="1.0.0">
  <analysisInformations analysisConfigurationId="analysis1" analysisDate="2019-03-10" author="i-Code CNES Analyzer" />
  <analysisFile language="fr.cnes.analysis.tools.languages.f90" fileName="basic_routines.f90" />
  <analysisFile language="fr.cnes.analysis.tools.analyzer.parsingError" fileName="basic_routines.f90" />
  <analysisRule analysisRuleId="F90.MET.ComplexitySimplified">
    <result resultId="1" fileName="basic_routines.f90" resultLine="8" resultTypePlace="method" resultNamePlace="module  procedure" resultValue="1.0" />
  </analysisRule>
  <analysisRule analysisRuleId="F90.MET.ComplexitySimplified">
    <result resultId="2" fileName="basic_routines.f90" resultLine="16" resultTypePlace="method" resultNamePlace="subroutine  Insertion_Sort_Int" resultValue="4.0" />
  </analysisRule>
...
  <analysisRule analysisRuleId="F90.TYPE.Integer">
    <result resultId="208" fileName="basic_routines.f90" resultLine="721" resultTypePlace="method" resultNamePlace="SUBROUTINE Insertion_Srt">
      <resultMessage>It misses the declaration SELECTED_INT_KIND in the initialisation of i, j</resultMessage>
    </result>
  </analysisRule>
</analysisProject>

**Comment by twenty-19** [comment]
You can close this issue, I think it's an error in the f90 files, I see fr.cnes.analysis.tools.analyzer.parsingError in version 3.1.0 for all the files that 3.2.0-dev isn't analyzing
