### ISSUE TITLE
PURE argument is crashing scanner in a set of FORTRAN routines

### ISSUE THREAD

**Issue by arthurvd** [lequal/i-CodeCNES#169]
### Expected behavior
Scanner should support the `pure` keyword for FORTRAN subroutines.

### Actual behavior
For the attached source file, the PURE keyword is not supported. The scanner crashes on it.
The subroutines are valid subroutines to have the `pure` keyword.
[xbeach_interp.F90.txt](https://github.com/lequal/i-CodeCNES/files/3739407/xbeach_interp.F90.txt)

### Steps to reproduce behavior
`icode.exe dflowfm_conv/**/* -o Results/results.xml`

### Detection version
3.1.0

**Comment by begarco** [comment]
`PURE` has been introduced in Fortran 95 whereas i-Code is limited to Fortran 77 and Fortran 90.

If you need i-Code to be compatible with Fortran 95, you can contribute to a new Fortran 95 plugin.

All information about how to create plugins for i-Code 4 is available here: https://github.com/lequal/icode-custom-plugin-example/wiki

**Comment by arthurvd** [comment]
Thanks for the analysis and explanation.
