### ISSUE TITLE
Combined standalone subroutine + module in same file is crashing scanner in FORTRAN file

### ISSUE THREAD

**Issue by arthurvd** [lequal/i-CodeCNES#170]
### Expected behavior
A FORTRAN source file may contain `module`s and 'standalone' `subroutine`'s in one and the same file.

### Actual behavior
For the attached source file, we have a `module m_fm_morstatistics`, followed by `subroutine sedmor_write_stats()` in one file `fm_morstatistics.f90`:
[fm_morstatistics.f90.txt](https://github.com/lequal/i-CodeCNES/files/3739478/fm_morstatistics.f90.txt)

The scanner crashes on it.
[1571146357496.log](https://github.com/lequal/i-CodeCNES/files/3739492/1571146357496.log)

[result.xml.txt](https://github.com/lequal/i-CodeCNES/files/3739495/result.xml.txt)

### Steps to reproduce behavior
`icode.exe dflowfm_conv/**/* -o Results/results.xml`

### Detection version
3.1.0

**Comment by begarco** [comment]
Not reproduced on i-Code 4. Please use i-Code 4.0 when released.

**Comment by arthurvd** [comment]
Thank you, we'll do that.
