### ISSUE TITLE
xml output - is it Junit xml?

### ISSUE THREAD

**Issue by twenty-19** [lequal/i-CodeCNES#199]
With regards to the xml test results from icode, is this Junit xml?

 - OS: linux
 - i-Code version: 4.0.0

**Comment by begarco** [comment]
Hi @twenty-19,
 
No, it is not. This is a custom XML format whose xsd file is available here: https://github.com/lequal/i-CodeCNES/blob/master/icode-ide/fr.cnes.analysis.tools.ui/resource/xsd/analysisResult.xsd

Do you need a JUnit format?

If you have any question, do not hesitate to ask it ;)
Benoît

**Comment by twenty-19** [comment]
Junit xml would be really useful, could then plug it straight into gitlab ci

Thanks for the reference to the xsd

**Comment by begarco** [comment]
You already have code analysis solution integrated into GitLab EE.

If you want to monitor code analysis results as tests into GitLab (have you any link about how to do it?), I suggest you to simply write an `xslt` to convert results from i-Code to JUnit format.

If you do so, we would appreciate a PR ;-)

On our side, we use SonarQube to gather i-Code (https://github.com/lequal/sonar-icode-cnes-plugin) results not GitLab.
