### ISSUE TITLE
Function declaration not handled

### ISSUE THREAD

**Issue by WaldoFR** [lequal/i-CodeCNES#52]
## Problem 
For shell languages, it's possible to declare a new function by several ways. However, some analyzers require the shell function to be declared with the keyword `function` before the function's name while it's optional.

## How to fix
Adding a new transition FUNCT to handle this declaration independantly to the keyword one on function declaration to retrieve function's name.

Also, make FUNCT  identifier using FNAME identifier as function's name instead of VAR one.

## Fix status

- [x] COM.DATA.LoopCondition *(FUNCT declarations handling)*
- [x] COM.DESIGN.ActiveWait *(FUNCT declarations handling)*
- [x] COM.FLOW.Abort *(FUNCT declarations handling)*
- [x] COM.FLOW.CaseSwitch *(FUNCT declarations handling)*
- [x] All rules : Verify FUNCT identifier to comply with FNAME.

**Comment by brigittehuynh** [comment]
In all, 47 rules out of 49 now have the FUNCT token. The 2 remaining ones doen't require localization as they check the first line of the file and any violation found can only be in MAIN PROGRAM.
The two rules are SH.INST.Interpreter and SH.DESIGN.Bash.
